### ISSUE TITLE
Duplicate entry in toml file

### ISSUE THREAD

**Issue by alessandro-molari** [Shougo/shougo-s-github#3]
In your plugins configuration you specified:

``` TOML
[[plugins]]
repository = 'Shougo/neossh.vim'
filetypes = 'vimfiler'
sources = 'ssh'

[[plugins]]
repository = 'Shougo/neossh.vim'
filetypes = 'vimshell'
```

Which results in a duplicate entry.. I don't know (and it's not documented) if that's possible.

Didn't you want to create a single entry instead?

``` TOML
[[plugins]]
repository = 'Shougo/neossh.vim'
filetypes = ['vimfiler', 'vimshell']
sources = 'ssh'
```

Thanks
